branches:
  only:
    - master
language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install gfortran g77 libcfitsio3-dev python-matplotlib python-pyfits python-scipy
install: 
  - pip install coveralls
  - pip install -r requirements.txt --use-mirrors
script:
  - nosetests --with-coverage --cover-package=unnamed
after_success:
  coveralls
notifications:
  email: false
